export const SET_PARKING_SPACES = 'SET_PARKING_SPACES';
export const ADD_CAR = 'ADD_CAR';
export const VACATE_PARKING_SPACE = 'VACATE_PARKING_SPACE';
export const ALLOCATE_PARKING_SPACE = 'ALLOCATE_PARKING_SPACE';
export const OPEN_EXIT_MODAL = 'OPEN_EXIT_MODAL';
export const CLOSE_EXIT_MODAL = 'CLOSE_EXIT_MODAL';
export const SAVE_STATE = 'SAVE_STATE';
export const SET_PARKING_SPACES_ARRAY = 'SET_PARKING_SPACES_ARRAY';